/**
 * Genesis Types - LLM Meta-Generation System
 *
 * Defines the interfaces for the "Genesis Phase" where LLM "mothers"
 * generate child agent specifications before simulation begins.
 *
 * Scientific Design:
 * - Each LLM can generate 5-100 child agents with unique characteristics
 * - Diversity enforcement prevents mode collapse
 * - Two modes: single-generation or evolutionary (multi-generation with feedback)
 *
 * @module genesis-types
 */

import type { PersonalityTrait } from './personalities';
import type { LLMType } from '../llm/types';

// =============================================================================
// Child Specification
// =============================================================================

/**
 * Resource priority preference for an agent.
 * Influences gathering and survival strategy.
 */
export type ResourcePriority = 'food' | 'energy' | 'material' | 'balanced';

/**
 * Specification for a child agent generated by an LLM mother.
 * Contains both required traits and optional narrative elements.
 */
export interface ChildSpecification {
  /** Unique descriptive name for the child agent */
  name: string;

  /** 1-2 sentence narrative backstory (optional, for flavor) */
  backstory?: string;

  /** Core personality trait - maps to existing personality system */
  personality: PersonalityTrait;

  /**
   * Risk tolerance level (0-1)
   * - 0.0-0.3: Risk-averse (cautious, defensive)
   * - 0.3-0.7: Moderate (balanced approach)
   * - 0.7-1.0: Risk-seeking (aggressive, exploratory)
   */
  riskTolerance: number;

  /**
   * Social orientation (0-1)
   * - 0.0-0.3: Solitary (prefers independence)
   * - 0.3-0.7: Moderate (selective interactions)
   * - 0.7-1.0: Highly social (seeks groups, cooperation)
   */
  socialOrientation: number;

  /** Primary resource focus */
  resourcePriority: ResourcePriority;

  /**
   * Strategic hint from mother (max 15 words)
   * Provides subtle guidance without prescribing exact behavior
   */
  strategicHint?: string;

  /**
   * Novel behavior to experiment with
   * Encourages diversity and innovation in agent strategies
   */
  innovationHook?: string;
}

// =============================================================================
// Genesis Configuration
// =============================================================================

/**
 * Selection criteria for evolutionary generation.
 * Determines which traits are favored across generations.
 */
export type SelectionCriteria =
  | 'survival_rate'      // Prioritize traits of survivors
  | 'cooperation_index'  // Prioritize cooperative behavior
  | 'wealth'             // Prioritize resource accumulation
  | 'longevity'          // Prioritize long-lived agents
  | 'social_capital';    // Prioritize relationship quality

/**
 * Configuration for evolutionary multi-generation mode.
 */
export interface EvolutionConfig {
  /** Number of generations to run (1-10) */
  generations: number;

  /** Criteria for selecting successful traits */
  selectionCriteria: SelectionCriteria;

  /** Percentage of top performers to use as feedback (0-1) */
  topPercentile: number;

  /** Simulation ticks per generation (default: 500) */
  ticksPerGeneration: number;
}

/**
 * Main configuration for the Genesis system.
 * Controls how LLM mothers generate child agents.
 */
export interface GenesisConfig {
  /** Whether genesis generation is enabled */
  enabled: boolean;

  /**
   * Number of children each mother should generate (5-100)
   * Higher numbers enable larger population studies
   */
  childrenPerMother: number;

  /** LLM types to use as "mothers" for generation */
  mothers: LLMType[];

  /**
   * Generation mode:
   * - 'single': One-shot generation, no feedback
   * - 'evolutionary': Multi-generation with selection pressure
   */
  mode: 'single' | 'evolutionary';

  /**
   * Minimum pairwise distance threshold for diversity (0-1)
   * Triggers retry if generated children are too similar
   */
  diversityThreshold: number;

  /**
   * Required archetype categories (at least one of each must be generated)
   * Examples: 'high_risk', 'high_cooperation', 'aggressive', 'cautious'
   */
  requiredArchetypes?: string[];

  /**
   * Temperature for LLM generation (default: 0.8)
   * Higher values encourage more diverse outputs
   */
  temperature?: number;

  /** Evolutionary configuration (only used if mode: 'evolutionary') */
  evolutionConfig?: EvolutionConfig;

  /** Random seed for reproducibility */
  seed?: number;
}

// =============================================================================
// Genesis Results
// =============================================================================

/**
 * Metadata about a genesis generation run.
 */
export interface GenesisMetadata {
  /** Prompt tokens used */
  promptTokens: number;

  /** Response tokens generated */
  responseTokens: number;

  /** Latency in milliseconds */
  latencyMs: number;

  /** Computed diversity score (0-1) */
  diversityScore: number;

  /** Number of retry attempts due to low diversity */
  retryCount: number;

  /** Timestamp of generation */
  generatedAt: number;

  /** Temperature used for generation */
  temperature: number;
}

/**
 * Result of a single LLM mother's generation.
 */
export interface GenesisResult {
  /** Unique ID for this generation run */
  id: string;

  /** LLM type that generated these children */
  motherType: LLMType;

  /** Generated child specifications */
  children: ChildSpecification[];

  /** Generation metadata */
  metadata: GenesisMetadata;

  /** Raw LLM response (for debugging/audit) */
  rawResponse?: string;
}

/**
 * Result of an evolutionary generation run.
 */
export interface EvolutionResult {
  /** Results from each generation */
  generations: GenesisResult[];

  /** Agent IDs that survived to the final generation */
  finalSurvivors: string[];

  /** Trait drift from generation 0 to N (cosine distance) */
  traitDrift: number;

  /** Whether traits converged to homogeneity */
  convergenceDetected: boolean;

  /** Summary statistics per generation */
  generationStats: GenerationStats[];
}

/**
 * Statistics for a single generation.
 */
export interface GenerationStats {
  generation: number;
  survivalRate: number;
  avgRiskTolerance: number;
  avgSocialOrientation: number;
  personalityDistribution: Record<PersonalityTrait, number>;
  topPerformers: string[];
}

// =============================================================================
// Validation Types
// =============================================================================

/**
 * Result of diversity validation check.
 */
export interface DiversityValidation {
  /** Whether diversity requirements are met */
  isValid: boolean;

  /** Computed diversity score */
  diversityScore: number;

  /** Minimum pairwise distance found */
  minPairwiseDistance: number;

  /** Maximum pairwise distance found */
  maxPairwiseDistance: number;

  /** Average pairwise distance */
  avgPairwiseDistance: number;

  /** Missing required archetypes */
  missingArchetypes: string[];

  /** Pairs that are too similar (for debugging) */
  similarPairs: Array<{
    child1: string;
    child2: string;
    distance: number;
  }>;
}

/**
 * Schema validation result for parsed child specifications.
 */
export interface SchemaValidation {
  isValid: boolean;
  errors: string[];
  validChildren: ChildSpecification[];
  invalidCount: number;
}

// =============================================================================
// Archetype Definitions
// =============================================================================

/**
 * Archetype requirement specification.
 * Defines what makes an agent qualify for an archetype.
 */
export interface ArchetypeRequirement {
  name: string;
  description: string;

  /** Personality traits that qualify */
  personalities?: PersonalityTrait[];

  /** Risk tolerance range [min, max] */
  riskToleranceRange?: [number, number];

  /** Social orientation range [min, max] */
  socialOrientationRange?: [number, number];

  /** Resource priorities that qualify */
  resourcePriorities?: ResourcePriority[];
}

/**
 * Predefined archetypes for diversity enforcement.
 */
export const ARCHETYPE_REQUIREMENTS: Record<string, ArchetypeRequirement> = {
  high_risk: {
    name: 'High Risk',
    description: 'Agents with risk tolerance > 0.7',
    riskToleranceRange: [0.7, 1.0],
  },
  low_risk: {
    name: 'Low Risk',
    description: 'Agents with risk tolerance < 0.3',
    riskToleranceRange: [0.0, 0.3],
  },
  high_cooperation: {
    name: 'High Cooperation',
    description: 'Social agents with high social orientation',
    personalities: ['cooperative', 'social'],
    socialOrientationRange: [0.7, 1.0],
  },
  aggressive: {
    name: 'Aggressive',
    description: 'Self-interested, competitive agents',
    personalities: ['aggressive'],
    riskToleranceRange: [0.5, 1.0],
  },
  cautious: {
    name: 'Cautious',
    description: 'Risk-averse, defensive agents',
    personalities: ['cautious'],
    riskToleranceRange: [0.0, 0.4],
  },
  explorer: {
    name: 'Explorer',
    description: 'Curious agents that seek new areas',
    personalities: ['explorer'],
  },
  balanced: {
    name: 'Balanced',
    description: 'Moderate in all dimensions',
    riskToleranceRange: [0.3, 0.7],
    socialOrientationRange: [0.3, 0.7],
    resourcePriorities: ['balanced'],
  },
};

// =============================================================================
// Default Configuration
// =============================================================================

/**
 * Default genesis configuration for experiments.
 */
export const DEFAULT_GENESIS_CONFIG: GenesisConfig = {
  enabled: false,
  childrenPerMother: 10,
  mothers: ['claude', 'gemini', 'codex'],
  mode: 'single',
  diversityThreshold: 0.3,
  requiredArchetypes: ['high_risk', 'low_risk', 'high_cooperation'],
  temperature: 0.8,
  seed: 42,
};

/**
 * Default evolution configuration.
 */
export const DEFAULT_EVOLUTION_CONFIG: EvolutionConfig = {
  generations: 3,
  selectionCriteria: 'survival_rate',
  topPercentile: 0.3,
  ticksPerGeneration: 500,
};
