import {test} from 'node:test';
import assert from 'node:assert/strict';
import {safeMetrics,evaluateAlarms} from './monitor-services.mjs';
const rules={minimumFiveMinuteRequests:20,maximumFiveXxFraction:0.05,maximumFiveMinuteRequests:5000,maximumFiveMinuteRenewalFailures:3,maximumRelayOverheadP95Ms:200,maximumUpstreamHttpP95Ms:30000,additionalUsageBudgetUsd:0};
const snapshot=()=>({services:{relay:{ready:true},admission:{ready:true}},metrics:{recent:{requests:100,httpStatusClasses:[0,100,0,0,0],ageSeconds:10,renewalFailures:0},relayOverhead:{p95UpperBoundMs:100},upstreamHttp:{p95UpperBoundMs:1000}},billing:{additionalUsageUsd:0,observedAt:Date.now()}});
test('alarm policy catches unavailable signals rather than declaring a pass',()=>{assert.deepEqual(evaluateAlarms(snapshot(),rules),[]);const missing=snapshot();missing.services.relay.ready=false;missing.metrics=null;missing.billing=null;assert.deepEqual(evaluateAlarms(missing,rules),['RELAY_UNAVAILABLE','METRICS_UNAVAILABLE_OR_STALE','BILLING_SIGNAL_UNAVAILABLE']);});
test('5xx, renewal failures, traffic, latency and additional spending trigger independently',()=>{const value=snapshot();value.metrics.recent={requests:6000,httpStatusClasses:[0,5000,0,0,1000],ageSeconds:0,renewalFailures:3};value.metrics.relayOverhead.p95UpperBoundMs=250;value.metrics.upstreamHttp.p95UpperBoundMs=60000;value.billing.additionalUsageUsd=0.01;assert.deepEqual(evaluateAlarms(value,rules),['ELEVATED_5XX','TRAFFIC_ANOMALY','RENEWAL_FAILURES','RELAY_LATENCY','UPSTREAM_HTTP_LATENCY','INFRASTRUCTURE_SPEND_ANOMALY']);});
test('safe projection excludes keys/content/identifiers and preserves unavailable measurements',()=>{const source={schemaVersion:1,scope:'current-coordinator-instance',storage:'RAM-only',requests:1,relayOverhead:{samples:1,meanMs:10,p95UpperBoundMs:10},upstreamHttp:{samples:0,meanMs:null,p95UpperBoundMs:null},admissionWorker:{samples:0,meanMs:null,p95UpperBoundMs:null},lastClosedFiveMinuteBucket:null,key:'private-key',prompt:'private-prompt',ip:'192.0.2.1',payload:{secret:'private-value'}};const result=safeMetrics(source);assert.equal(result.upstreamHttp.meanMs,null);assert.equal(result.providerProcessingMs,null);const text=JSON.stringify(result);assert(!text.includes('private'));assert(!text.includes('192.0.2.1'));assert.equal(safeMetrics({...source,requests:'private-key'}),null);});
test('incomplete rules and stale billing/metric signals cannot produce a healthy configuration',async()=>{const {validRules}=await import('./monitor-services.mjs');assert.equal(validRules({}),false);assert.equal(validRules(rules),true);assert.equal(validRules({...rules,maximumFiveXxFraction:2}),false);const value=snapshot();value.metrics.recent.ageSeconds=301;value.billing.observedAt=Date.now()-300001;assert.deepEqual(evaluateAlarms(value,rules),['METRICS_UNAVAILABLE_OR_STALE','BILLING_SIGNAL_UNAVAILABLE']);});
