import { afterEach, expect, test } from 'bun:test';
import { SCENARIOS } from '../services/scenarios';
import { resetRuntimeConfig, setRuntimeConfig, getRuntimeConfig } from '@simagents/engine/config';
import { SimEngine } from '@simagents/engine/engine/engine';
import { resetStore } from '@simagents/engine/engine-memory/store';
afterEach(() => { resetRuntimeConfig(); resetStore(); });
for (const scenario of SCENARIOS) test(`${scenario.id} preset seeds its advertised conditions without inference`, async () => {
  resetRuntimeConfig();
  setRuntimeConfig(scenario.overrides);
  let requests = 0;
  const engine = new SimEngine({ providerFactory: () => ({ kind: 'fixture', decide: async () => { requests++; return { type: 'sleep', params: { duration: 1 } }; } }) });
  await engine.seed({ roster: [{ id: 'fixture', name: 'Fixture', provider: 'baseline_rule', modelId: 'baseline_rule', color: '#888888' }] });
  const agent = engine.getState().agents[0];
  expect(agent.balance).toBe(scenario.overrides.agent.startingBalance!);
  expect(agent.hunger).toBe(scenario.overrides.agent.startingHunger!);
  expect(agent.energy).toBe(scenario.overrides.agent.startingEnergy!);
  expect(getRuntimeConfig().needs.hungerDecay).toBe(scenario.overrides.needs.hungerDecay!);
  expect(requests).toBe(0);
  expect(engine.snapshot().configuration?.overrides.agent?.startingBalance).toBe(agent.balance);
});
